#!/bin/sh
# set orientation for Waveshare 3.5inch RPi LCD (B)

set -e

NEW_DEGREE=$1
CONFIG_FILE="/boot/waveshare.txt"

die() {
        printf '\033[1;31mERROR:\033[0m %s\n' "$@" >&2  # bold red
        exit 1
}

[ "$(id -u)" -eq 0 ] || _sudo='sudo'

if [ -z "$NEW_DEGREE" ]
        then
                die 'No degree supplied, please choose from: 0, 90, 180, 270'
fi

set_orientation_0() {
	$_sudo /bin/sh <<-EOF
        sed -i 's/^dtoverlay=waveshare35b.*/dtoverlay=waveshare35b/' $CONFIG_FILE || echo "dtoverlay=waveshare35b" >> $CONFIG_FILE
        cp /etc/X11/xorg.conf.d/99-calibration.conf-35b /usr/share/X11/xorg.conf.d/99-calibration.conf
EOF
}

set_orientation_90() {
	$_sudo /bin/sh <<-EOF
        sed -i 's/^dtoverlay=waveshare35b.*/dtoverlay=waveshare35b:rotate=180/' $CONFIG_FILE || echo "dtoverlay=waveshare35b:rotate=180" >> $CONFIG_FILE
        cp /etc/X11/xorg.conf.d/99-calibration.conf-35b-90 /usr/share/X11/xorg.conf.d/99-calibration.conf
EOF
}

set_orientation_180() {
	$_sudo /bin/sh <<-EOF
        sed -i 's/^dtoverlay=waveshare35b.*/dtoverlay=waveshare35b:rotate=270/' $CONFIG_FILE || echo "dtoverlay=waveshare35b:rotate=270" >> $CONFIG_FILE
        cp /etc/X11/xorg.conf.d/99-calibration.conf-35b-180 /usr/share/X11/xorg.conf.d/99-calibration.conf
EOF
}

set_orientation_270() {
	$_sudo /bin/sh <<-EOF
        sed -i 's/^dtoverlay=waveshare35b.*/dtoverlay=waveshare35b:rotate=0/' $CONFIG_FILE || echo "dtoverlay=waveshare35b:rotate=0" >> $CONFIG_FILE
        cp /etc/X11/xorg.conf.d/99-calibration.conf-35b-270 /usr/share/X11/xorg.conf.d/99-calibration.conf
EOF
}

case $NEW_DEGREE in
          0) set_orientation_0;;
         90) set_orientation_90;;
        180) set_orientation_180;;
        270) set_orientation_270;;
          *) die 'Invalid degree, please choose from: 0, 90, 180, 270';;
esac

cat >&2 <<-EOF
        ---
        Set orientation to $NEW_DEGREE complete, please reboot to take effect.

EOF
